<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CydLAN.Networking</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CydLAN.Protocol\CydLAN.Protocol.csproj" />
  </ItemGroup>
</Project>
